common: &common
  dev_key: AI39si6ESvHkACD9wiBYnU7uaL6loVZs7DDFDVPmDg22DNk2MGVycBjGlj19hB_GUkx-As5nV-6257Jh_EAKbflZIfB6SsvCjg
  username:  schizophrenicworld
  password:  ch4rpentier
  
test:
  <<: *common
development:
  <<: *common
production:
  <<: *common
